//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fbxImporter.proto
namespace fbxImporter
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector2")]
  public partial class Vector2 : global::ProtoBuf.IExtensible
  {
    public Vector2() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UPolygon")]
  public partial class UPolygon : global::ProtoBuf.IExtensible
  {
    public UPolygon() {}
    
    private readonly global::System.Collections.Generic.List<fbxImporter.Vector3> _coordinates = new global::System.Collections.Generic.List<fbxImporter.Vector3>();
    [global::ProtoBuf.ProtoMember(1, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.Vector3> coordinates
    {
      get { return _coordinates; }
    }
  
    private readonly global::System.Collections.Generic.List<fbxImporter.Vector2> _texUV = new global::System.Collections.Generic.List<fbxImporter.Vector2>();
    [global::ProtoBuf.ProtoMember(2, Name=@"texUV", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.Vector2> texUV
    {
      get { return _texUV; }
    }
  
    private readonly global::System.Collections.Generic.List<fbxImporter.Vector3> _normal = new global::System.Collections.Generic.List<fbxImporter.Vector3>();
    [global::ProtoBuf.ProtoMember(3, Name=@"normal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.Vector3> normal
    {
      get { return _normal; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UPolygons")]
  public partial class UPolygons : global::ProtoBuf.IExtensible
  {
    public UPolygons() {}
    
    private readonly global::System.Collections.Generic.List<fbxImporter.UPolygon> _polygon = new global::System.Collections.Generic.List<fbxImporter.UPolygon>();
    [global::ProtoBuf.ProtoMember(1, Name=@"polygon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.UPolygon> polygon
    {
      get { return _polygon; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UGeometricTransform")]
  public partial class UGeometricTransform : global::ProtoBuf.IExtensible
  {
    public UGeometricTransform() {}
    
    private fbxImporter.Vector3 _translation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"translation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fbxImporter.Vector3 translation
    {
      get { return _translation; }
      set { _translation = value; }
    }
    private fbxImporter.Vector3 _rotation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fbxImporter.Vector3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private fbxImporter.Vector3 _scaling;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scaling", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fbxImporter.Vector3 scaling
    {
      get { return _scaling; }
      set { _scaling = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UMaterialIndex")]
  public partial class UMaterialIndex : global::ProtoBuf.IExtensible
  {
    public UMaterialIndex() {}
    
    private string _mapping = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mapping
    {
      get { return _mapping; }
      set { _mapping = value; }
    }
    private string _referenceMode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"referenceMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string referenceMode
    {
      get { return _referenceMode; }
      set { _referenceMode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _indexList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"indexList", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> indexList
    {
      get { return _indexList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UTextureInfo")]
  public partial class UTextureInfo : global::ProtoBuf.IExtensible
  {
    public UTextureInfo() {}
    
    private int _materialId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"materialId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int materialId
    {
      get { return _materialId; }
      set { _materialId = value; }
    }
    private string _diffusePath = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diffusePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string diffusePath
    {
      get { return _diffusePath; }
      set { _diffusePath = value; }
    }
    private fbxImporter.Vector2 _diffuvScale = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diffuvScale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fbxImporter.Vector2 diffuvScale
    {
      get { return _diffuvScale; }
      set { _diffuvScale = value; }
    }
    private fbxImporter.Vector2 _diffvTranslation = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diffvTranslation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fbxImporter.Vector2 diffvTranslation
    {
      get { return _diffvTranslation; }
      set { _diffvTranslation = value; }
    }
    private bool _diffswapUV = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"diffswapUV", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool diffswapUV
    {
      get { return _diffswapUV; }
      set { _diffswapUV = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UMeshNode")]
  public partial class UMeshNode : global::ProtoBuf.IExtensible
  {
    public UMeshNode() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private fbxImporter.UPolygons _Polygons = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Polygons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fbxImporter.UPolygons Polygons
    {
      get { return _Polygons; }
      set { _Polygons = value; }
    }
    private fbxImporter.UGeometricTransform _geoTras = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"geoTras", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fbxImporter.UGeometricTransform geoTras
    {
      get { return _geoTras; }
      set { _geoTras = value; }
    }
    private int _childrenNums;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"childrenNums", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int childrenNums
    {
      get { return _childrenNums; }
      set { _childrenNums = value; }
    }
    private readonly global::System.Collections.Generic.List<fbxImporter.UMeshNode> _children = new global::System.Collections.Generic.List<fbxImporter.UMeshNode>();
    [global::ProtoBuf.ProtoMember(5, Name=@"children", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.UMeshNode> children
    {
      get { return _children; }
    }
  
    private fbxImporter.UMaterialIndex _materialList = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"materialList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fbxImporter.UMaterialIndex materialList
    {
      get { return _materialList; }
      set { _materialList = value; }
    }
    private readonly global::System.Collections.Generic.List<fbxImporter.UTextureInfo> _textureList = new global::System.Collections.Generic.List<fbxImporter.UTextureInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"textureList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.UTextureInfo> textureList
    {
      get { return _textureList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"USceneNode")]
  public partial class USceneNode : global::ProtoBuf.IExtensible
  {
    public USceneNode() {}
    
    private int _meshNums;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meshNums", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int meshNums
    {
      get { return _meshNums; }
      set { _meshNums = value; }
    }
    private readonly global::System.Collections.Generic.List<fbxImporter.UMeshNode> _meshList = new global::System.Collections.Generic.List<fbxImporter.UMeshNode>();
    [global::ProtoBuf.ProtoMember(2, Name=@"meshList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fbxImporter.UMeshNode> meshList
    {
      get { return _meshList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}